name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: make install

    - name: Run the application
      run: |
        make run &
        sleep 90 # Give the server time to start up

    - name: Test server response
      run: |
        curl -f http://localhost:3000 || exit 1
